In [25]:
import numpy as np
data = np.load('/home/asap7772/asap7772/real_data_kitchen/bridge_data_numpy/toykitchen1/put_lid_on_stove/out.npy', allow_pickle=True)

In [28]:
len(data)

51

In [20]:
data[0]['actions']

[array([-1.80662152e-10,  2.31665086e-10,  4.12681903e-11, -3.49094041e-07,
        -3.62770034e-08, -2.01658347e-07,  1.00000000e+00]),
 array([ 0.00870225,  0.00906358, -0.00783842, -0.01812336, -0.00927057,
        -0.0309878 ,  1.        ]),
 array([ 0.00425056,  0.00847445, -0.00751861,  0.01426434, -0.01509091,
        -0.04088911,  1.        ]),
 array([ 0.0052349 ,  0.00867287, -0.00491543,  0.01961494, -0.01937395,
        -0.02851258,  1.        ]),
 array([ 0.00597809,  0.00546831, -0.00338407,  0.00475101, -0.01375349,
        -0.04013541,  1.        ]),
 array([ 3.64310437e-03,  7.88026941e-04, -3.60715659e-03,  8.43364503e-03,
        -1.70897027e-02, -1.14683949e-02,  1.00000000e+00]),
 array([ 8.65754150e-05,  1.29824740e-03, -4.22181671e-03, -1.35932618e-02,
        -1.26870670e-02, -1.86262506e-02,  8.35898000e-01]),
 array([ 0.00252158, -0.00044527, -0.00548404, -0.00459586, -0.01010175,
        -0.0346457 ,  0.313797  ]),
 array([-0.0006602 , -0.00191094, -0.0034578

In [21]:
DL = data[0]['observations']